export const ICON_OPTIONS = [
  { value: "heart", label: "Corazón" },
  { value: "heart-pulse", label: "Pulso" },
  { value: "ambulance", label: "Ambulancia" },
  { value: "stethoscope", label: "Estetoscopio" },
  { value: "hospital", label: "Hospital" },
  { value: "kit-medical", label: "Botiquín" },
  { value: "monitor", label: "Monitor" },
  { value: "lungs", label: "Respiración" },
  { value: "bed", label: "Cama" },
  { value: "user-doctor", label: "Médico" },
  { value: "microscope", label: "Microscopio" },
  { value: "handshake", label: "Apretón de manos" },
  { value: "certificate", label: "Certificado" },
  { value: "shield", label: "Escudo" },
  { value: "shield-check", label: "Escudo con check" },
  { value: "lightbulb", label: "Idea" },
  { value: "headset", label: "Soporte" },
  { value: "medal", label: "Medalla" },
  { value: "truck", label: "Entrega" },
  { value: "graduation-cap", label: "Capacitación" },
];
